{"ID": "badaeacf-9b92-425e-b562-4aa78a76b05c", "effective_cve": "CVE-2021-28861", "image": {"exact": "docker.io/anchore/test_images@sha256:808f6cf3cf4473eb39ff9bb47ead639d2ed71255b75b9b140162b58c6102bcc9"}, "label": "??", "package": {"name": "platform-python", "version": "3.6.8-47.el8_6"}, "timestamp": "2022-11-01T16:07:40+00:00", "tool": "grype@v0.51.0-7-gfcce63b", "user": "westonsteimel", "vulnerability_id": "CVE-2021-28861"}