{"ID": "8a8f9b4e-602b-4af8-a886-bbf12a2a53d2", "effective_cve": "CVE-2021-3733", "image": {"exact": "docker.io/anchore/test_images@sha256:0825acea611c7c5cc792bc7cc20de44d7413fd287dc5afc4aab9c1891d037b4f"}, "label": "TP", "package": {"name": "python3", "version": "3.8.10-r0"}, "timestamp": "2023-02-13T17:39:12+00:00", "tool": "grype@v0.56.0-30-g17e11ac", "user": "westonsteimel", "vulnerability_id": "CVE-2021-3733"}