{"ID": "201130f5-9b37-47ef-acfd-0180b147ced5", "effective_cve": "CVE-2021-28861", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "python3.4", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2024-05-16T17:13:28.155185+00:00", "tool": "grype@v0.77.4", "user": "wagoodman", "vulnerability_id": "CVE-2021-28861"}