{"ID": "37946150-a6b0-4377-9c57-b644102b7741", "effective_cve": "CVE-2019-2811", "image": {"exact": "docker.io/anchore/test_images@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4"}, "label": "FP", "package": {"name": "mysql", "version": "2.18.1"}, "timestamp": "2022-09-14T17:48:08+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2019-2811"}