{"ID": "3341e411-e497-4987-8fd7-2c5607de5bc6", "effective_cve": "CVE-2018-1000117", "image": {"exact": "docker.io/anchore/test_images@sha256:ff80ae5de3446939639f3fbb58f66f641e2da1d881bdab704d9237424f64417f"}, "label": "TP", "package": {"name": "python", "version": "3.6.3a-vZ9"}, "timestamp": "2023-01-19T13:41:28+00:00", "tool": "grype@v0.55.0", "user": "westonsteimel", "vulnerability_id": "CVE-2018-1000117"}