{"ID": "dafe5ac8-8851-4891-92f6-30495b1ef4ab", "effective_cve": "CVE-2021-3733", "image": {"exact": "docker.io/anchore/test_images@sha256:ff80ae5de3446939639f3fbb58f66f641e2da1d881bdab704d9237424f64417f"}, "label": "FP", "package": {"name": "python3", "version": "3.8.10-r0"}, "timestamp": "2023-03-08T11:15:56+00:00", "tool": "grype@v0.59.0", "user": "westonsteimel", "vulnerability_id": "CVE-2021-3733"}