{"ID": "29844ef0-5f1b-47e8-9460-e480147c60aa", "effective_cve": "CVE-2021-4189", "image": {"exact": "docker.io/almalinux@sha256:cd49d7250ed7bb194d502d8a3e50bd775055ca275d1d9c2785aea72b890afe6a"}, "label": "TP", "package": {"name": "platform-python", "version": "3.6.8-41.el8.alma"}, "timestamp": "2022-11-01T22:52:10+00:00", "tool": "grype@v0.51.0", "user": "westonsteimel", "vulnerability_id": "CVE-2021-4189"}