{"ID": "c1680d47-1ea6-47f4-ac8b-70d05561c681", "effective_cve": "CVE-2019-12900", "image": {"exact": "docker.io/python@sha256:5e96e03a493a54904aa8be573fc0414431afb4f47ac58fbffd03b2a725005364"}, "label": "TP", "package": {"name": "python", "version": "3.8.0"}, "timestamp": "2022-09-29T22:20:51+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2019-12900"}